const EVENT_NAME_PREFIX = 'ORHUN_';

const AUTH_TOKEN_READY = `${EVENT_NAME_PREFIX}AUTH_TOKEN_READY`;

/**
 * event.detail = canvas|null
 */
const SCREENSHOT_READY = `${EVENT_NAME_PREFIX}SCREENSHOT_READY`;

const PREPARE_PAYLOAD_REQUEST = `${EVENT_NAME_PREFIX}PREPARE_PAYLOAD_REQUEST`;
const RETRIEVE_PAYLOAD_REQUEST = `${EVENT_NAME_PREFIX}RETRIEVE_PAYLOAD_REQUEST`;
const RETRIEVE_PAYLOAD_RESPONSE = `${EVENT_NAME_PREFIX}RETRIEVE_PAYLOAD_RESPONSE`;

export {AUTH_TOKEN_READY, SCREENSHOT_READY, PREPARE_PAYLOAD_REQUEST, RETRIEVE_PAYLOAD_REQUEST, RETRIEVE_PAYLOAD_RESPONSE}
