const EVENT_NAME_PREFIX = 'ULAK_';

const AUTH_TOKEN_READY_EVENT_NAME = `${EVENT_NAME_PREFIX}AUTH_TOKEN_READY`;

const PREPARE_PAYLOAD_REQUEST = `${EVENT_NAME_PREFIX}PREPARE_PAYLOAD_REQUEST`;
const RETRIEVE_PAYLOAD_REQUEST = `${EVENT_NAME_PREFIX}RETRIEVE_PAYLOAD_REQUEST`;
const RETRIEVE_PAYLOAD_RESPONSE = `${EVENT_NAME_PREFIX}RETRIEVE_PAYLOAD_RESPONSE`;

export {AUTH_TOKEN_READY_EVENT_NAME, PREPARE_PAYLOAD_REQUEST, RETRIEVE_PAYLOAD_REQUEST, RETRIEVE_PAYLOAD_RESPONSE}
